version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ordersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3k1jq1inpnjq"
s3_prefix = "ordersapi"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
