AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi

Globals:
  Function:
    Runtime: java11
    CodeUri: ordersapi
    MemorySize: 512
    Timeout: 30
    Environment:
      ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type : AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
  CreateOrderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ca.josue.aws.lambda.apis.CreateOrderLambda::createOrder
      Architectures:
        - x86_64
      Events:
        OrderEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: POST

  ReadOrdersFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: ca.josue.aws.lambda.apis.ReadOrdersLambda::getOrders
      Architectures:
        - x86_64
      Events:
        OrderEvent:
          Type: Api
          Properties:
            Path: /orders
            Method: GET